# Generated by Django 6.0.1 on 2026-01-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='start',
            new_name='start_time',
        ),
    ]
