# Generated by Django 6.0.1 on 2026-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_end_entry_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.TextField(default=None, null=True),
        ),
    ]
