# Generated by Django 6.0.1 on 2026-01-19 01:45

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_client_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='start_time',
            field=models.DateTimeField(default=backend.models._utc_now),
        ),
    ]
