# Generated by Django 6.0.1 on 2026-01-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_entry_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
