# Generated by Django 6.0.1 on 2026-02-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_entry_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='editedfrom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_from', to='backend.entry'),
        ),
        migrations.AddField(
            model_name='entry',
            name='editedto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='edited_to', to='backend.entry'),
        ),
    ]
